CREATE TABLE "analysis_count_attempts" (
	"request_key" text PRIMARY KEY NOT NULL,
	"guide_id" text NOT NULL,
	"run_id" text NOT NULL,
	"batch_index" integer NOT NULL,
	"generation_ordinal" integer NOT NULL,
	"status" text NOT NULL,
	"payload" jsonb NOT NULL,
	CONSTRAINT "analysis_count_identity_check" CHECK (("analysis_count_attempts"."request_key" ~ '^[a-f0-9]{64}$' AND "analysis_count_attempts"."batch_index" BETWEEN 0 AND 5 AND "analysis_count_attempts"."generation_ordinal" BETWEEN 0 AND 1 AND "analysis_count_attempts"."payload"->>'operation' = 'countTokens' AND "analysis_count_attempts"."payload"->>'bindingHash' ~ '^[a-f0-9]{64}$' AND "analysis_count_attempts"."payload"->>'scopeKey' ~ '^[a-f0-9]{64}$') IS TRUE),
	CONSTRAINT "analysis_count_status_check" CHECK ("analysis_count_attempts"."status" IN ('reserved','sending','settled','uncertain','overrun','released')),
	CONSTRAINT "analysis_count_maximum_check" CHECK ((("analysis_count_attempts"."payload"->'maximum'->>'requests')::numeric = 1 AND ("analysis_count_attempts"."payload"->'maximum'->>'inputTokens')::numeric > 0 AND ("analysis_count_attempts"."payload"->'maximum'->>'outputTokens')::numeric = 0 AND ("analysis_count_attempts"."payload"->'maximum'->>'costMicrousd')::numeric > 0 AND ("analysis_count_attempts"."payload"->>'accountingInputRate')::numeric > 0 AND ("analysis_count_attempts"."payload"->>'accountingInputRate')::numeric <= 9007199254740991) IS TRUE),
	CONSTRAINT "analysis_count_requests_check" CHECK ((("analysis_count_attempts"."payload"->'maximum'->>'requests')::numeric BETWEEN 0 AND 9007199254740991 AND ("analysis_count_attempts"."payload"->'charged'->>'requests')::numeric BETWEEN 0 AND ("analysis_count_attempts"."payload"->'maximum'->>'requests')::numeric AND trunc(("analysis_count_attempts"."payload"->'maximum'->>'requests')::numeric) = ("analysis_count_attempts"."payload"->'maximum'->>'requests')::numeric AND trunc(("analysis_count_attempts"."payload"->'charged'->>'requests')::numeric) = ("analysis_count_attempts"."payload"->'charged'->>'requests')::numeric) IS TRUE),
	CONSTRAINT "analysis_count_inputTokens_check" CHECK ((("analysis_count_attempts"."payload"->'maximum'->>'inputTokens')::numeric BETWEEN 0 AND 9007199254740991 AND ("analysis_count_attempts"."payload"->'charged'->>'inputTokens')::numeric BETWEEN 0 AND ("analysis_count_attempts"."payload"->'maximum'->>'inputTokens')::numeric AND trunc(("analysis_count_attempts"."payload"->'maximum'->>'inputTokens')::numeric) = ("analysis_count_attempts"."payload"->'maximum'->>'inputTokens')::numeric AND trunc(("analysis_count_attempts"."payload"->'charged'->>'inputTokens')::numeric) = ("analysis_count_attempts"."payload"->'charged'->>'inputTokens')::numeric) IS TRUE),
	CONSTRAINT "analysis_count_outputTokens_check" CHECK ((("analysis_count_attempts"."payload"->'maximum'->>'outputTokens')::numeric BETWEEN 0 AND 9007199254740991 AND ("analysis_count_attempts"."payload"->'charged'->>'outputTokens')::numeric BETWEEN 0 AND ("analysis_count_attempts"."payload"->'maximum'->>'outputTokens')::numeric AND trunc(("analysis_count_attempts"."payload"->'maximum'->>'outputTokens')::numeric) = ("analysis_count_attempts"."payload"->'maximum'->>'outputTokens')::numeric AND trunc(("analysis_count_attempts"."payload"->'charged'->>'outputTokens')::numeric) = ("analysis_count_attempts"."payload"->'charged'->>'outputTokens')::numeric) IS TRUE),
	CONSTRAINT "analysis_count_costMicrousd_check" CHECK ((("analysis_count_attempts"."payload"->'maximum'->>'costMicrousd')::numeric BETWEEN 0 AND 9007199254740991 AND ("analysis_count_attempts"."payload"->'charged'->>'costMicrousd')::numeric BETWEEN 0 AND ("analysis_count_attempts"."payload"->'maximum'->>'costMicrousd')::numeric AND trunc(("analysis_count_attempts"."payload"->'maximum'->>'costMicrousd')::numeric) = ("analysis_count_attempts"."payload"->'maximum'->>'costMicrousd')::numeric AND trunc(("analysis_count_attempts"."payload"->'charged'->>'costMicrousd')::numeric) = ("analysis_count_attempts"."payload"->'charged'->>'costMicrousd')::numeric) IS TRUE)
);
--> statement-breakpoint
ALTER TABLE "analysis_count_attempts" ADD CONSTRAINT "analysis_count_attempts_guide_id_run_id_analysis_reservations_guide_id_run_id_fk" FOREIGN KEY ("guide_id","run_id") REFERENCES "public"."analysis_reservations"("guide_id","run_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "analysis_count_slot_unique" ON "analysis_count_attempts" USING btree ("guide_id","run_id","batch_index","generation_ordinal");--> statement-breakpoint
CREATE INDEX "analysis_count_pending_idx" ON "analysis_count_attempts" USING btree ("status","guide_id","run_id");